# Generated by Django 3.2.14 on 2023-03-01 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20230301_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventinstance',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
