# Generated by Django 3.2.14 on 2023-03-01 13:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_eventinstance_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventinstance',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
